# Generated by Django 5.2.6 on 2025-09-29 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('image', '0004_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('wallpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.wallpaper')),
            ],
            options={
                'indexes': [models.Index(fields=['wallpaper', 'user'], name='account_boo_wallpap_f1ad87_idx')],
                'unique_together': {('wallpaper', 'user')},
            },
        ),
    ]
