# Generated by Django 5.2.6 on 2025-09-28 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('wallpaper', models.ImageField(upload_to='wallpapers/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/%Y/%m/%d/')),
                ('type', models.CharField(choices=[('PC', 'Компьютер'), ('PHONE', 'Телефон')], default='PC', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallpapers', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='wallpapers', to='image.tag')),
            ],
        ),
        migrations.CreateModel(
            name='WallpaperLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='image.wallpaper')),
            ],
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['created_at', 'title'], name='image_wallp_created_0af061_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wallpaperlike',
            unique_together={('wallpaper', 'user')},
        ),
    ]
