# Generated by Django 5.2.6 on 2025-09-28 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallpaperlike',
            index=models.Index(fields=['wallpaper', 'user'], name='image_wallp_wallpap_c4aa98_idx'),
        ),
    ]
