# Generated by Django 5.2.6 on 2025-09-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_wallpaperlike_image_wallp_wallpap_c4aa98_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
